### PR TITLE
pt-br.json

### PR DESCRIPTION
**Pull request by Heart-BreakOne**
Brazilian Portuguese translation

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
Hey,

Thanks for the translation! Just wanted to ask, since it's a Brazillian Portuguese translation, should the file be named `pt-br.json` rather than `pt.json`? Or are you sure `pt` and `pt-br` would have the same translation in this case?

**Comment by Heart-BreakOne** [comment]
"pt-br" would be more suitable, there are differences in the dialect.

**Comment by KockaAdmiralac** [comment]
Alright, could you rename the file in your commit then?

**Comment by Heart-BreakOne** [comment]
I believe I have it done..

**Comment by KockaAdmiralac** [comment]
You renamed the pull request, not the file you're commiting :P 

You just have to rename the file on your local machine and then recommit it to your fork.

**Comment by KockaAdmiralac** [comment]
Thanks!

**Pull request merged**
